HPの（多分）完成品
misc-org/misc-mdn.dev pull request #10
Opened 2024-04-26 15:16 UTC by shiki-01

基本の変更点は以下の通りです、お二人にレビューをお願いしたいです！

- 全体のレイアウトの大幅修正
- ブログをmicroCMSを使って連携
- タグを使ってソートやフィルター機能の追加
- Aboutの基本変えない部分はコンポーネント化
- Aboutに文章の追記（一昨年の部活動紹介スライドを参考）

コーディングのきれいさとかに関してはほぼ初心者なので、後学のためにも色々教えていただきたいです！
文章の誤字脱字等も確認お願いします！
PC / スマホ どちらにもある程度対応している（はず）ので、もしスタイリング漏れ等ありましたらそちらも！

※GitHubのアイコンが、[こちら](https://github.com/logos)を見るとこの素材以外使うなって書いてあるのですが、[Iconify](https://icon-sets.iconify.design/mdi/?query=github)を見ると Apache 2.0 がついていたりややこしいので使っても大丈夫かのご意見も聞きたいです…！

see:

- [`src/lib/components/Footer.svelte`](https://github.com/misc-org/misc-mdn.dev/blob/add/pages/src/lib/components/Footer.svelte)

2024-04-26 17:16 UTC, wappon28dev requested changes
おおむね LGTM です！！！  

すこしコメントが多くなってしまいましたが, 本当に Figma 通りの部分が多く, めちゃ上出来です！  凄いです！！！  
コメントの部分は修正のコミットを積んでいただいて, 該当の Conversion の下らへんにある “as Resolved” 的なボタンを押せばスムーズに PR レビューができると思います.

リリースが待ちきれないですね！ 🚀

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogLink.svelte
> +  export let ogpImg: { url: string } | null;
このコンポーネントは単一のブログに飛べるようにするためのカードのようですね.  
ということは, このコンポーネントは単一のブログのデータがあればレンダーできそうですね.

もしかしたら今後スキーマが変わる可能性があって, 型が変わってしまう可能性があります. なので, このコンポーネントの Props はできるだけ少なく, 型はできるだけ再利用したほうが保守性が高くなりそうですね！
次のように変更してみてはどうでしょう？

- `src/lib/components/BlogLink.svelte`

  ```diff
  <script lang="ts">
  +  import type { EndPoints } from "$lib/utils/types/microcms";

  -  export let id: string;
  -  export let title: string;
  -  export let publishedAt: string;
  -  export let tags: string[];
  -  export let ogpImg: { url: string } | null;
  +  export let blogData: EndPoints["get"]["blogs"];
  +  const { id, ogpImg, publishedAt, tags, title } = blogData;

    // ...
  ```

- `src/lib/components/BlogPage.svelte`

  ```diff
  {#each sortedAndFilteredBlogs as blogData}
  -  <BlogLink
  -    id={blog.id}
  -    title={blog.title}
  -    publishedAt={blog.publishedAt}
  -    tags={blog.tags}
  -    ogpImg={blog.ogpImg}
  -  />
  + <BlogLink {blogData} />
  {/each}
  ```

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogLink.svelte
> +        <img src="https://placehold.jp/150x150.png" alt="ogp" />
デフォルトの OGP 画像どうしましょうね.  もしよければ 1200px×630px で作っていただけると嬉しいです.

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogLink.svelte
> +        <img src={ogpImg.url} alt={title} />
```suggestion
        <img
          src={ogpImg.url}
          alt={title}
          height={ogpImg.height}
          width={ogpImg.width}
        />
```

アクセシビリティ的にも [CLS - web.dev ↗](https://web.dev/articles/cls?hl=ja) 的にも, `img` タグには height と width 属性を指定すると良い感じです.  
実は microCMS の画像フィールドには画像の URL の他に, 縦幅と横幅が返される [^1] ので, それを使ってみてはどうでしょう？

[^1]: [メディア管理 - microCMS docs ↗](https://document.microcms.io/manual/media-management#h3ec2b82f0c)

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogLink.svelte
> +    aspect-ratio: 100 / 52.5;
```suggestion
```

↑ の縦横の指定により, `aspect-ratio` の指定は不要かも？

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogLink.svelte
> +    border-radius: 5px;
定義が分かりにくて申し訳ないですが, SCSS 変数を使ってあげるなら
```suggestion
    border-radius: $radii-md;
```
が近いかも？

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogPage.svelte
> +  let blogListContents = blogs.blogList.contents;
`import type { EndPoints } from "$lib/utils/types/microcms";` を追加した上で,

```suggestion
  export let blogs: EndPoints["gets"]["blogs"];
  export let limit: number = 10;

  let blogListContents = blogs.contents;
```

としてあげると, microCMS が返す型が流れてきます！  そのおかげで L30 や L33 などの型注脚が不要になります. 🎉

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogPage.svelte
> +    "_migrated",
```suggestion
```
これは内部用のフラグなので消してﾖｼ! <img src="https://github.com/misc-org/misc-mdn.dev/assets/86721991/8582ad59-5ec3-47fc-bb0a-a67617096792" height="20" width="20" />

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogPage.svelte
> +      </select>
もしお時間あれば ThemeSelector.svelte の [`<Select>` - Bits UI ↗](https://www.bits-ui.com/docs/components/select) を参考にプルダウンメニューを実装してあげると, サイトにもっと馴染むかもです！  ぜひ！

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/BlogPage.svelte
> +      <Button on:click={handlePublishedAtClick}>投稿日</Button>
```suggestion
      <Button on:click={handlePublishedAtClick}>公開日</Button>
```
PublishedAt を訳すなら “公開日” のほうが近いかもですね.  実際, BlogLink のアイキャッチ画像の下にある日付は “公開” になっていますね.

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/Button.svelte
> +  const dispatch = createEventDispatcher();
Svelte らしい Emit の機能を使っていて素晴らしいです！ 😄

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/utils/types/microcms.ts
> +export type Tags = Blogs["tags"][number];
```suggestion
```

配列からユニオン型を得る良いコードですね！

ちなみにこのファイルは microCMS の API スキーマから自動生成[^1]  → ESLint 修正によって自動生成されています！  
なので, この行の Type Alias は, `$ npm run generate:cms` で簡単に上書きされてしまいます.  
良さげなファイルを `types/` の中につくってそこで定義してもらうか, 使うところで別途作ってあげると良いかもです.

###### ちなみにこの `Tags` は `BlogPage.svelte` の L47 で使われていますが, `Tags[]` ってしちゃっているので, あんまり意味ないかも？

[^1]: [MicroCMSのAPIをTypeScriptで型カッチリに実装する - Zenn ↗](https://zenn.dev/sora_kumo/articles/2876c8f98eca56#typescript%E3%81%AE%E5%9E%8B%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90)

2024-04-26 17:16 UTC, wappon28dev commented on src/routes/about/+page.svelte
It's so cool! 👍

2024-04-26 17:16 UTC, wappon28dev commented on src/routes/about/+page.svelte
> +        font-size: 1.2em;
```suggestion
        font-size: $size-lg;
```
SCSS 変数のお気持ちに揃えるなら, `$size-lg` あたりが近そうかな.

2024-04-26 17:16 UTC, wappon28dev commented on src/routes/blogs/[slug]/+page.svelte
> +  }
`formatDate()` は `src/lib/components/BlogLink.svelte` でも再登場していますね！  DRY 原則に則って別ファイルに切り出してみてはどうでしょう？

2024-04-26 17:16 UTC, wappon28dev commented on src/lib/components/About.svelte
> +      自分の作ったソフトが誰かの役に立つ喜びを知って欲しい。<br />
めちゃ細かい上, もともとが間違っていたかもですが, ここでの “欲しい” は形式動詞なので, ひらがなのほうが良いかもです. (>_<;)

```suggestion
      自分の作ったソフトが誰かの役に立つ喜びを知ってほしい。<br />
```

2024-04-26 17:16 UTC, wappon28dev commented on src/routes/about/+page.svelte
> +      <li>MicroCMS</li>
```suggestion
      <li>microCMS</li>
```
microCMS の m は小文字です警察 👮

2024-04-26 22:46 UTC, shiki-01 commented on src/lib/components/BlogPage.svelte
> +  let blogListContents = blogs.blogList.contents;
こちらに修正したところ、
```patch
32    filterTag === "All" || blog.tags.includes(filterTag),
```
の部分で"All"が入るから形ちがうぞって言われたので、
```patch
- 32    filterTag === "All" || blog.tags.includes(filterTag),
+ 32    filterTag === "All" || blog.tags.includes(filterTag as Tags),
```
としてfilterTagにも型を（All入るけど）指定しました

2024-04-26 22:48 UTC, shiki-01 commented on src/lib/components/BlogPage.svelte
> +      </select>
めっちゃ探してました！！！！！！！！！！！

2024-04-27 02:55 UTC, shiki-01 reviewed
へるぷです！
記事が全く出てこなくなってしまいます！

2024-04-27 02:55 UTC, shiki-01 commented on src/lib/components/BlogPage.svelte
> +  console.log(blogs.contents);
ここで`blogs`自体にはアクセスできるのですが、`blogs.contens`などの中の要素にアクセスしようとすると`undifined`が返ってきてしまいます…
どうすればいいでしょうか…

ちなみに、 `blogs` の型を変更したので、[`routes/blogs/+page.svelte`](https://github.com/misc-org/misc-mdn.dev/pull/10/commits/87756504ef4a9d1b9b8c0dbddc9c1195adfdcf7b#diff-31c54e514b040fad7b11e025623e6706d95047619c09d40e08dcdfbd6519c28c)でも`data`の型を変更してます

2024-04-27 03:34 UTC, wappon28dev commented on src/lib/components/BlogPage.svelte
> +  console.log(blogs.contents);
https://github.com/misc-org/misc-mdn.dev/blob/87756504ef4a9d1b9b8c0dbddc9c1195adfdcf7b/src/lib/components/BlogPage.svelte#L35-L50

L37 で `blogListContents` に対して `sort()` していますね.  そして, `sort()` は破壊的な操作です.[^1]  (`append()` のようにもとの配列を変えてしまう)  
`blogListContents` はあくまで `blogs.contents` への **値** ではなく, **参照** を持っているので...
1. 何らかの理由で L44 の default に行き着き `0` と再代入
1. おそらく `blogListContents == null` の意図で書いたであろう L36 の if の中身は falsy なので, `[]` と再代入
1. `blogListContents` が変更される
1. `blogs.contents` が変更される
みたいな流れかもです.

このバグを直すには, まずソートやフィルターを行うまえに `[...blogListContents]` としてシャローコピーを取るか, 次のようにデータ構造を変えてみても良いかもです.

---

![image](https://github.com/misc-org/misc-mdn.dev/assets/86721991/7331e73f-500c-4c6c-a93b-9769e90dea04)  
これは Google Maps の経路の絞り込み UI なのですが, 実装したい機能は左か右かで言えば複数選択の左のほうが近いかと思います.

[Checkbox - Bits UI ↗](https://www.bits-ui.com/docs/components/checkbox) を参考に, Tags を複数選択で絞り込んでみてはどうでしょう？  
```ts
// TypeScript 側で...
export const tagsData = {
  お知らせ: { icon: "mdi:bell" },
  ブログ: { icon: "mdi:book" },
  作品紹介: { icon: "mdi:palette" },
  活動報告: { icon: "mdi:account" },
  "1 年生": { icon: "mdi:numeric-1" },
  "2 年生": { icon: "mdi:numeric-2" },
  "3 年生": { icon: "mdi:numeric-3" },
} as const satisfies Record<
  ArrayElem<Blogs["tags"]>,
  {
    icon: string;
  }
>;

// Svelte 側で...
const filterTags: Array<keyof typeof tags> = [];
$: _filtered = blogListContents.filter(({tags}) => {
  if (filterTags.length === 0) return true;
  return filterTags.some((tag) => tags.includes(tag));
});
// ...
```
そうすると fillter で絞り込みがしやすいかと思います.  また, 現在実装している `All` については `fillterTags` を `[]` にするだけですね.  ぜひ！


[^1]: [【JavaScript】破壊的メソッドの非破壊的な書き方 - Zenn](https://zenn.dev/cryptobox/articles/ec99edaaa16b7b#sort())

2024-04-27 04:40 UTC, SatooRu65536 reviewed
すごい...
変更しなければいけない部分はもう見当たらないから細かいところだけ
好みもあるだろうし従う必要はないよ

2024-04-27 04:40 UTC, SatooRu65536 commented on src/lib/components/Footer.svelte
> +    @media (max-width: 768px) {
`/src/lib/styles/responsive.scss` 等を追加して
```scss
@mixin mobile {
  @media (max-width: 768px) {
    @content;
  }
}
```

↓にしてあげると分かりやすいかも
```suggestion
    @include mobile {
```
※他も同様に

2024-04-27 04:40 UTC, SatooRu65536 commented on src/lib/components/BlogLink.svelte
> +  <a href={`/blogs/${id}`}><h3>{title}</h3></a>
基本的にインライン要素の aタグ の中にブロック要素の hタグ を入れるのは良くないから
```suggestion
  <h3><a href={`/blogs/${id}`}>{title}</a></h3>
```
とした方が良い

2024-04-27 04:40 UTC, SatooRu65536 commented on src/lib/components/BlogLink.svelte
> +  </div>
これは `Open Graph Protocol` のことならば OGP ではないから `thumbnail` とかの方がいいかも...?
`Open Graph Protocol` でなくても何を指すか分かりやすい名前の方がいい

```suggestion
  <div class="thumbnail">
    <a href={`/blogs/${id}`}>
      {#if ogpImg}
        <img
          src={ogpImg.url}
          alt={title}
          height={ogpImg.height}
          width={ogpImg.width}
        />
      {:else}
        <img src="https://placehold.jp/1200x630.png" alt="thumbnail" />
      {/if}
    </a>
  </div>
```

2024-04-27 04:40 UTC, SatooRu65536 commented on src/lib/components/BlogPage.svelte
> +  function handlePublishedAtClick() {
いつ使うかを表す `handlePublishedAtClick` より、処理の内容を説明する `toggleSortOrder` などの方がいいかも

```suggestion
  function toggleSortOrder() {
```
※これはやや宗教なので必ずしも従う必要はない

2024-04-27 04:40 UTC, SatooRu65536 commented on src/lib/components/BlogPage.svelte
> +  #sort {
idセレクタはどのセレクタより強力だから、
classセレクタで問題ない場合は idセレクタは避けた方がいいかも
(他も同様)
```suggestion
  .sort {
```
※これもやや宗教なので従う必要はない

js で使う場合や
`.container > .box > .... > .text` みたいに深くなりすぎる場合は全然いいと思う

2024-04-27 07:21 UTC, shiki-01 commented on src/lib/components/BlogPage.svelte
> +  console.log(blogs.contents);
ブログが表示されなかったのは、多分おそらく型を~適当に~間違って指定してしまったためだと思います！

https://github.com/misc-org/misc-mdn.dev/blob/87756504ef4a9d1b9b8c0dbddc9c1195adfdcf7b/src/lib/components/BlogLink.svelte#L1-L6

ここの
```ts
 const { id, title, publishedAt, tags, ogpImg } = blogData; 
```
がリアクティブじゃなかったり

https://github.com/misc-org/misc-mdn.dev/blob/87756504ef4a9d1b9b8c0dbddc9c1195adfdcf7b/src/lib/components/BlogPage.svelte#L13

あたりの型指定が良くなかったらしいです！

2024-04-27 07:32 UTC, SatooRu65536 approved these changes, later dismissed

2024-04-27 09:43 UTC, shiki-01 commented
頂いた分の変更はほぼクリアしました！
お二人とも本当にありがとうございます！！

2024-04-28 01:35 UTC, SatooRu65536 requested changes

2024-04-28 01:35 UTC, SatooRu65536 commented on src/lib/components/About.svelte
> +      }
見落としてたけど、同じセレクターはまとめた方がSCSSらしい書き方になるよ
```suggestion
      > p {
        font-size: $size-lg;
        line-height: 1.5;

        @include mobile {
          font-size: $size-xs;
        }
      }
```
他にもあるかも

2024-04-28 09:46 UTC, SatooRu65536 approved these changes, later dismissed

2024-04-28 14:59 UTC, wappon28dev submitted a review, later dismissed
これだけ！　LTGM!!!

2024-04-28 14:59 UTC, wappon28dev commented on src/routes/blogs/[slug]/+page.svelte
> +    <img src={data.detail.ogpImg.url} alt={data.detail.title} />
```suggestion
    <img
      src={data.detail.ogpImg.url}
      alt={data.detail.title}
      height={data.detail.ogpImg.height}
      width={data.detail.ogpImg.width}
    />
```

https://github.com/misc-org/misc-mdn.dev/pull/10#discussion_r1581253163 と同様, width と height を渡してあげると嬉しいです.

2024-04-28 14:59 UTC, wappon28dev commented on src/lib/components/BlogPage.svelte
> +          class="flex h-input items-center gap-x-0.5 rounded-card-sm border border-border bg-background-alt px-[4px] py-1 shadow-mini"
この行は TailwindCSS の書き方のスタイルのようですね.  このプロジェクトでは使っていないので, 削除して OK です.  
L96 も同様です.

2024-04-28 15:10 UTC, wappon28dev approved these changes

2024-04-28 15:11 UTC, merged

2024-04-28 15:11 UTC, wappon28dev commented
お疲れ様でした！！！