✨ create いっぱい追加してしまった…
misc-org/misc-mdn.dev pull request #11
Opened 2024-04-30 09:34 UTC by shiki-01

・プレビュー
・Icon使えるように
・リストきれいに
・ハイライトコードつけれるように

色々追加してしまったので、一応こっちも確認もらおうかと…！

see:

- [`src/lib/utils/blogParsre`](https://github.com/misc-org/misc-mdn.dev/blob/add/highlight/src/lib/utils/services/blogParser.ts)　ブログを一旦パーサーかけてからそれぞれ描写してます
- [`src/routes/blogs/[slug]/+page.server.ts`](https://github.com/misc-org/misc-mdn.dev/blob/add/highlight/src/routes/blogs/%5Bslug%5D/%2Bpage.server.ts)　画面プレビュー用に draftKey があれば [`getDraftContentDetail`](https://github.com/misc-org/misc-mdn.dev/blob/add/highlight/src/lib/utils/services/microcms.ts#L52)を実行するように変更しました
- [`src/routes/blogs/[slug]/+page.svelte`](https://github.com/misc-org/misc-mdn.dev/blob/add/highlight/src/routes/blogs/%5Bslug%5D/%2Bpage.svelte)　Icon とか ハイライト とか色々デザイン面の変更です

メインはここらへんです！

2024-05-01 15:25 UTC, shiki-01 commented
思ったより問題が見つかってしまったのでもうしばしお待ちして欲しいです！

終わりしだい連絡します🙇‍♂️

2024-05-05 03:24 UTC, shiki-01 commented
色々制限したりオリジナルクラスも追加したので、microCMS 関連の tips を追加しました！
一応こちらも確認お願いします。

see:

- [`docs/microcms/tips.md`](https://github.com/misc-org/misc-mdn.dev/blob/add/highlight/docs/microcms/tips.md)

2024-05-21 15:26 UTC, wappon28dev requested changes
少しコード量が多いですね.  
追加したい機能は主に...

- `span.icon` を Iconify のアイコンに変更する
- コードブロックのハイライト
- 画像の属性の取得？
  な感じですね. microCMS からの HTML のパーサーを書いているようですが, 実は `lib/utils/middlewares` に rewriter というものがあります.

---

説明不足であれば申し訳ないのですが, rewriter は HTML を書き換える役割です.  
例えば, `add-anchor-copy.ts` と `add-anchor-copy.test.ts` を見てみましょう.

```ts
export function addAnchorCopy(html: string): string {
  const $ = load(html);
  const $header = $("h2, h3");
  // ...
```

`rewriteHTML` 関数から `addAnchorCopy` が呼ばれ, `html` に生の HTML が渡されます.  
`load` で HTML をパースし, `$` に格納されています. また, `$` は jQuery のように使えるので, `$("h2, h3")` で `h2` と `h3` を取得しています.
その後, HTML を書き換えて, `$.html()` で文字列に戻しています.

このように rewriter で HTML を書き換えてから Svelte でレンダーする流れを取ると, パーサーを書く必要がなく, もう少しコードが短くなると思います！

---

<details>
<summary>HTML からすべての画像の属性を得る</summary>

```ts
// `src/lib/utils/middlewares/rewriters/figure.ts` とか
import { load } from "cheerio";

export function processFigure(html: string): string {
  const $ = load(html);
  const $img = $("img");

  $img.each((_, elem) => {
    const $elem = $(elem);
    const img = $elem.attr("src");
    const alt = $elem.attr("alt");
    const width = $elem.attr("width");
    const height = $elem.attr("height");

    // ...

    $(elem).replaceWith(/* ... */);
  });

  return $.html();
}
```

</details>

---

<details>
<summary>また, Svelte コンポーネントを使いたいこともあるでしょう.</summary>

```ts
// `src/lib/utils/middlewares/rewriters/icons.ts` とか
// `span.icon` を Iconify のアイコンに変更する
import Icon from "@iconify/svelte";
import type { ComponentProps } from "svelte";
import logoTitle from "$lib/assets/icons/logo-title";

type IconProps = ComponentProps<Icon>["icon"];

const specialIcons: Record<string, IconProps> = {
  logoTitle: logoTitle,
};

export function injectIconify(): void {
  if (document == null) {
    throw new Error(
      "document is not defined. This fn should be called after `onMount`",
    );
  }

  document.querySelectorAll("span.icon").forEach((elem) => {
    const iconName = elem.textContent;
    if (iconName == null) {
      throw new Error("icon is not defined");
    }

    const icon: IconProps = specialIcons[iconName] ?? iconName;

    new Icon({
      target: elem,
      hydrate: true,
      props: { icon },
    });
  });
}
```

```ts
// `src/lib/utils/middlewares/rewrite-html.ts` とか適当な場所
export function injectComponents(): void {
  const arr: Array<() => void> = [injectIconify]; // 今後はここに注入したい Svelte コンポーネントを追加

  arr.forEach((fn) => {
    fn();
  });
}
```

の 2 つを用意して,

```svelte
// ...
onMount(() => {
  injectComponents();
});
```

とすればパーサーを書かなくても, Svelte コンポーネントを使うことができます！

</details>

---

な感じで...

1. パーサーを使わずに
1. ページ側の HTML の注入は次のように

   ```svelte
   <article>
     <div id="date-at">
       <p>公開日：{formatDate(data.detail.publishedAt)}</p>
       <p>更新日：{formatDate(data.detail.updatedAt)}</p>
     </div>
       <!-- eslint-disable-next-line svelte/no-at-html-tags -->
       {@html rewriteHTML(data.detail.content)}
   </article>
   ```

書き直してみると嬉しいなー！と.  分からないことがあればお聞きください！

2024-05-21 21:44 UTC, shiki-01 commented
はっ…こんなものが…l
急いで書き換えたいと思いますっ

レビューありがとうございますです！

2024-05-23 08:38 UTC, shiki-01 commented on src/lib/utils/middlewares/rewrite-html.ts
> +export function injectComponents(): void {
書いてみたのですが、 Icon を追加しても、取得できないんですよね…

`src/lib/utils/middlewares/rewriters/icons.ts` 
```typescript
document.querySelectorAll("span.icon")    //null
document    //全部のHTML
```
となってしまい、表示ができず…どうすればいいでしょう？

2024-05-24 17:30 UTC, wappon28dev commented on src/lib/utils/middlewares/rewrite-html.ts
> +export function injectComponents(): void {
ここらへんですね.

https://github.com/misc-org/misc-mdn.dev/blob/e20faf7adeae2261e16a57736a46029e2773d604/src/routes/blogs/%5Bslug%5D/%2Bpage.svelte#L17-L21

マウント時に,
1. (不要ですが) パースをする
2. コンポーネントの注入する
3. コンテンツをロードしたかのフラグ (`isContentLoaded`) を立てる
をしていますが,

https://github.com/misc-org/misc-mdn.dev/blob/e20faf7adeae2261e16a57736a46029e2773d604/src/routes/blogs/%5Bslug%5D/%2Bpage.svelte#L65-L67

を見ると, `isContentLoaded` が Falsy のとき, microCMS から渡された HTML は表示されないのではなく, DOM としてマウントされません.

つまり, コンポーネントの注入先がないってことです.
ちなみに, `isContentLoaded` は何に使っているのでしょうか？  不要であれば削除しちゃって問題ないかと思います！

2024-05-24 17:32 UTC, wappon28dev commented on src/lib/utils/middlewares/rewrite-html.ts
> +export function injectComponents(): void {
ちなみに Prettier と ESLint が効いてないと思われます.  VSCode の拡張機能か, `yarn fmt` や `yarn lint` していただけると！

2024-05-24 22:26 UTC, shiki-01 commented on src/lib/utils/middlewares/rewrite-html.ts
> +export function injectComponents(): void {
@wappon28dev 

ありがとうございます！

ちなみになんですけど、
https://github.com/misc-org/misc-mdn.dev/blob/e20faf7adeae2261e16a57736a46029e2773d604/src/routes/blogs/%5Bslug%5D/%2Bpage.svelte#L65-L67
のところで、`{@html} can lead to XSS attack.` と出てしまうのですが、`dompurify` とかで一応サニタイズした方がいいですかね？

2024-05-25 05:17 UTC, wappon28dev commented on src/lib/utils/middlewares/rewrite-html.ts
> +export function injectComponents(): void {
サニタイズの必要性ですが, 一般にインラインや script タグで js が含まれているなどが原因になります.
しかし, 今回その HTML の大本は microCMS で, 開発者が把握できる (他のユーザーの入力が一切含まれていない) ので, まあここはサニタイズしなくても良いかな～～～ という感じです.
(今回 SSG するので, ビルド後は `@html` の箇所は注入されたあとの状態になりますし)

心配なのであれば, CSP など設定しておくと良いかも と思いました.

https://github.com/misc-org/misc-mdn.dev/blob/1b44558e3372882e74be91a9d9db43c39d7ad5a3/src/routes/blogs/%5Bslug%5D/%2Bpage.svelte#L39-L40

2024-05-26 02:41 UTC, wappon28dev commented on docs/microcms/tips.md
> +```
パーサーについての補足は不要かもです！

2024-05-26 02:43 UTC, wappon28dev commented on docs/microcms/tips.md
> +
ここも……？

挙動をこのようにするならば, このままでも良いかもです.

2024-05-26 03:04 UTC, shiki-01 commented on docs/microcms/tips.md
> +
一応

https://github.com/misc-org/misc-mdn.dev/blob/3a7d0b7535530ead0722d3065c1ac48c817f3600/src/lib/utils/middlewares/rewriters/icons.ts#L26-L31

の部分でアイコンサイズの変更はできるようにしてあるんので、こちらはこのままにしようかなと！

（記法だけ少し変わったので修正しました）

2024-05-26 03:51 UTC, wappon28dev requested changes
マージまであとちょっとかと思います！  あとちょっとお願いします！

2024-05-26 03:51 UTC, wappon28dev commented on package.json
> +    "@skeletonlabs/tw-plugin": "^0.4.0",
この 2 つの依存関係はもはや使われていないようです.
- `$ npm remove @skeletonlabs/skeleton`
- `$ npm remove @skeletonlabs/tw-plugin`
で削除しちゃいましょう.

2024-05-26 03:51 UTC, wappon28dev commented on docs/microcms/tips.md
> +
```suggestion
```

`parser.ts` はもう無いので, ここの記述は削除していただけると！

2024-05-26 03:51 UTC, wappon28dev commented on src/routes/blogs/[slug]/+page.server.ts
> +  }
この記述だと, 403 や 500 などのエラーを握りつぶしていまいます. if 文のあと, もう一度 `error` を Throw すると良いかもです.
また, try-catch 文をなくした場合でも `+error.svelte` がエラーページを描画してくれるので, そもそも try-catch 文は不要かもです.

2024-05-26 03:51 UTC, wappon28dev commented on src/routes/blogs/[slug]/+page.server.ts
> +      res = await getContentDetail("blogs", slug);
もはや仕様変更レベルを見逃していてとってもスミマセンですが, 1 つ良いでしょうか？

現在, microCMS へのアクセスを減らすためにも, 高速化のためにも, 現在 `/blogs/[slug]` を含めたすべてのページが Pre-render されます.  
https://github.com/misc-org/misc-mdn.dev/blob/3a7d0b7535530ead0722d3065c1ac48c817f3600/src/routes/%2Blayout.ts#L1-L2

しかし, Pre-render されてほしいページは既に公開されているページ (microCMS で “公開” したページ) です.  
そのことに対して画面プレビューもこのページ (厳密にはパス) で処理させる場合, その仕組み上 microCMS へのアクセスが必要で, Pre-render の意図と矛盾してしまいます.  
ちなみに現在の状態だと, Svelte の Pre-render**er** がこのページを走査してビルドするとき, `draftKey` パラメーターは付与せずレンダーするので, microCMS から “画面プレビュー” しても, どのページでも Not Found を返します！

まとめますと,
- `/blogs/[slug]` は Pre-render するようにして, `getContentDetail` を返す
- `/drafts/blogs/[slug]?draftKey=...` は Pre-render しないようにして, `getDraftContentDetail` を返す
のような設計にすると良いと思います！

パスによって Pre-render するかしないかの設定は [Page options - SvelteKit Docs ↗](https://kit.svelte.dev/docs/page-options#prerender) を参考にすると良いと思います！

2024-05-26 03:51 UTC, wappon28dev commented on docs/microcms/tips.md
> +まず、HTML要素を表現するための型が定義されています。これらは、HTMLの各要素（段落、見出し、リスト、テーブルなど）を表現するためのものです。例えば、`MainElement` 型は、HTMLの主要な要素を表現します。これらの型は、パーサーがHTMLを解析し、特定の形式に変換する際に使用されます。
```suggestion

```

ここの記述も古くなっているかもです.

2024-05-26 04:14 UTC, shiki-01 commented on src/routes/blogs/[slug]/+page.server.ts
> +      res = await getContentDetail("blogs", slug);
一応自分なりに書いてみましたがもし何かあれば…！

see:
- [`src/routes/+layout.ts`](https://github.com/misc-org/misc-mdn.dev/blob/add/highlight/src/routes/%2Blayout.ts)

2024-06-03 07:00 UTC, wappon28dev commented on src/routes/+layout.ts
> +};
また遅くなってしまいました.  すみません. 🙇 

---

おっと.  あまり見慣れない書き方をしているようですね！  
この `const prerender = ...` というものはあくまで SvelteKit に Pre-render するかしないかの設定値を公開しているだけなので, 関数が呼び出されたりすることも, `request` に URL が入ったりすることはありません.  ためしに, `$ npm run build` などしてみてください.  おそらくビルドがコケると思います.

前回のコメントどおり,

> まとめますと,
> - `/blogs/[slug]` は Pre-render するようにして, `getContentDetail` を返す
> - `/drafts/blogs/[slug]?draftKey=...` は Pre-render しないようにして, `getDraftContentDetail` を返す
> 
> のような設計にすると良いと思います！

を実装してみましょう.  
具体的には, `/routes/blogs/[slug]/+page.svelte` や `/routes/drafts/blogs/[slug]/+page.svelte` を作る感じです！  分からなくなってしまったらぜひお伝えください！  私が代わりにコミットしようと思います.

see: [Page options - SvelteKit Docs ↗︎](https://kit.svelte.dev/docs/page-options#prerender)

2024-06-03 09:38 UTC, shiki-01 commented on src/routes/+layout.ts
> +};
レビューありがとうございます！
いろいろやってみたのですが、そもそも `/routes/blogs/[slug]/+page.svelte` が Pre-render してくれなく…

もしよかったらコミットお願いしてもいいでしょうか X(

2024-06-15 20:42 UTC, wappon28dev reviewed
こんにちは.  数日お待たせしてすみませんでした. 🙇 

パス `/routes/blogs/[slug]/+page.svelte` が Pre-render できない理由を調査をしたところ, Blog 一覧を表示する BlogPage コンポーネントが原因だと分かりました.

ページネーションのための Limit が悪さをしているようです:

https://github.com/misc-org/misc-mdn.dev/blob/72fdc38b7af038c08167786ebcdbeea29eff6022/src/lib/components/BlogPage.svelte#L23-L24

このコードは, `page` に初期値である `1` が代入されているので, このコンポーネントの `onMount` が呼び出されるまで `0` になってしうことで, For が回らなく, 記事が 1 つも無い判定になっていたようです. (実際, ページロードのときに `記事がありません` が見えますね.)

これがどう Pre-render に響いていくのかというと, ズバリ Pre-render の仕組みが関わっています. 公式ドキュメント ([Page options - SvelteKit Docs ↗](https://kit.svelte.dev/docs/page-options#entries)) によると,

> ...SvelteKit will prerender `/` and `/blog`, and in the process discover links like `<a href="/blog/hello-world">` which give it new pages to prerender.

のように記載があり, `<a>` タグの発見可能が必要 → `BlogLink` コンポーネントの描画が必要 → `BlogPage` コンポーネントで `BlogLink` コンポーネントの For が必要 → `limit` の初期値が `0` でない... のような感じに繋がっていることが分かりました.

これを解決するために, ページネーションを削除し, 初期状態ですべての記事がちゃんと描画されるようにするコミットを積んでおきました！ 🙌 
あと, コンポーネント名や記法の変更を主とするリファクタリングもしておきました！ ♻️ 

あとは, Draft 機能が不完全であったため, これも Pre-render されるように記事表示のコンポーネントを `/blogs/[slug]` と共通化し, 適切なエラーハンドリングも追加しておきました！

@shiki-01 が積んだコミットの最後から, 私の積んだコミットの最後までの File Changes を見て, 不明瞭や不明なコードがあれば, ぜひお聞きくださいね.

2024-06-16 07:41 UTC, shiki-01 commented
確認しました！
自分が色々謎の設定をしてしまっていたようですね…勉強になります。
そして、お忙しいなかコミットもしていただきありがとうございます！

全体的に理解できたので、私からは特にないですが、既知の問題だったダミー画像を作成しておきました。
コミット確認いただけると！

2024-06-16 16:47 UTC, wappon28dev approved these changes
DummyImage のコミット OK です！  LGTM!
ついでに, Hover 時のアニメーションを普通の画像とおなじように設定しておきました！

長い間お疲れ様でした！  仕様の練りが足りなかったのか, 何度かコメントしたり, Reject したりして申し訳なかったです.

近いうちに, GitHub Actions を使って本番環境へデプロイしたいですね.  Figma でのデザインから着実に実装してくれたので, 立派なサイトになりそうです.

2024-06-16 16:47 UTC, merged