📝 docs 追加
misc-org/misc-mdn.dev pull request #9
Opened 2024-04-07 08:19 UTC by wappon28dev

README (`/README.md`) とコードの歩き方 (`/docs/tips.md`) を書いてみました.  
足りないところや伝わりづらいところ, 誤字脱字などレビューをお願いしたいです！

2024-04-07 08:43 UTC, SatooRu65536 requested changes

2024-04-07 08:43 UTC, SatooRu65536 commented on README.md
> +- Node.js v21
Node の奇数版は CURRENT(安定版ではない) から `v20` にするべきかと
同様に `nvm use v21` `mise use node@21`も変更する必要がありそう

2024-04-07 08:49 UTC, wappon28dev commented on README.md
> +- Node.js v21
たしかに LTS (現時点: v20) にすべきですね……！

2024-04-07 09:03 UTC, shiki-01 reviewed
どうせならそのまま approve しないほうがいいのかなと思ったのですが、そこまでの知識がありませんでした

2024-04-07 09:03 UTC, shiki-01 commented on docs/tips.md
> +Vite の共通オプションの SCSS プロパティーに, すべての SCSS ファイル (/スタイルブロック) に use するよう設定しているからです.
```suggestion
Vite の共通オプションの SCSS プロパティーに, すべての SCSS ファイル (スタイルブロック) に use するよう設定しているからです.
```

さっぱりぴーまんなのでこれくらいしか書けませんが、シンプル書き間違いなのか、何か意味があればすみませんorz

2024-04-07 09:11 UTC, wappon28dev commented on docs/tips.md
> +Vite の共通オプションの SCSS プロパティーに, すべての SCSS ファイル (/スタイルブロック) に use するよう設定しているからです.
変な記号が入っちゃってました 🙃

2024-04-07 18:32 UTC, SatooRu65536 approved these changes

2024-04-07 19:00 UTC, SatooRu65536 commented
@wappon28dev 
`package-lock.json` が更新されていないかも
`npm ci` すると 怒られる
> npm ERR! notsup Required: {"node":"21.x"}
npm ERR! notsup Actual:   {"npm":"10.4.0","node":"v20.12.0"}

https://github.com/misc-org/misc-mdn.dev/blob/69007067990755512b20a1580d6e9f28ea1af3c4/package-lock.json#L49-L51

2024-04-09 21:57 UTC, shiki-01 approved these changes

2024-04-10 08:55 UTC, merged